improve resiliency of restore operations

diff --git a/apps/cloudos/templates/restore.sh.erb b/apps/cloudos/templates/restore.sh.erb
--- a/apps/cloudos/templates/restore.sh.erb
+++ b/apps/cloudos/templates/restore.sh.erb
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Usage: restore <backup files>
+# Usage: restore.sh [app1] [app2] [...]
 #
 # Environment variables that must be defined:
 # AWS_ACCESS_KEY_ID -- the S3 access key
@@ -9,9 +9,15 @@
 # S3_BUCKET -- the S3 bucket that hold the backups
 # BACKUP_KEY -- path to a file containing the encryption key
 #
+# If no apps are specified, then all apps will be restored.
+#
+
+TEMP_FILES=""
+RESTORE_APPS="$@"
 
 function die () {
   echo "$@"
+  rm -rf ${TEMP_FILES}
   exit 1
 }
 
@@ -37,11 +43,13 @@ fi
 DEFAULT_KEY="/etc/.cloudos"
 if [ $(echo -n ${BACKUP_KEY} | head -c 1) != "/" ] ; then
   # BACKUP_KEY contains the actual key. write it to the default key location.
-  echo -n ${BACKUP_KEY} > ${DEFAULT_KEY} && BACKUP_KEY=${DEFAULT_KEY}
+  echo -n ${BACKUP_KEY} > ${DEFAULT_KEY} || die "Error writing backup key to ${DEFAULT_KEY}"
+  BACKUP_KEY=${DEFAULT_KEY}
 
 elif [ "${BACKUP_KEY}" != "${DEFAULT_KEY}" ] ; then
   # BACKUP_KEY contains the path to the key. write it to the default key location
-  cat ${BACKUP_KEY} > ${DEFAULT_KEY} && rm -f ${BACKUP_KEY} && BACKUP_KEY=${DEFAULT_KEY}
+  cat ${BACKUP_KEY} > ${DEFAULT_KEY} && rm -f ${BACKUP_KEY} || die "Error copying backup key to ${DEFAULT_KEY}"
+  BACKUP_KEY=${DEFAULT_KEY}
 fi
 chmod 600 ${DEFAULT_KEY}
 
@@ -57,8 +65,10 @@ function fetch_app_tarball () {
 
   # todo: determine closest region by geo
   aws s3 cp --region us-east-1 ${s3_tar} ${RESTORE_DIR}/${app_name} 2> /dev/null 1>&2 || die "Error retrieving tarball: ${s3_tar}"
-  openssl enc -d -aes256 -pass file:${BACKUP_KEY} -in ${RESTORE_DIR}/${app_name}/${file_name} -out ${RESTORE_DIR}/${app_name}/$tar_name || die "Error decrypting tarball: ${file_name}"
-  tar xjfp ${RESTORE_DIR}/${app_name}/${tar_name} -C ${RESTORE_DIR}/${app_name} || die "Error unrolling tarball: ${tar_name}"
+  tarball="${RESTORE_DIR}/${app_name}/${tar_name}"
+  openssl enc -d -aes256 -pass file:${BACKUP_KEY} -in ${RESTORE_DIR}/${app_name}/${file_name} -out ${tarball} || die "Error decrypting tarball: ${file_name}"
+  tar xjfp ${tarball} -C ${RESTORE_DIR}/${app_name} || die "Error unrolling tarball: ${tar_name}"
+  TEMP_FILES="${TEMP_FILES} $(tar tjf ${tarball} | egrep -v "^tmp/$" | egrep "^tmp/" | sed -e 's,^tmp/,/tmp/,g' )"
 
   # for sanity: tar can unroll things to /tmp /var /etc or /home and it preserves the permissions from the backup dir
   # so after unrolling an app tarball, ensure that permissions are back to normal
@@ -71,121 +81,63 @@ function fetch_app_tarball () {
 S3_ROOT="${S3_BUCKET}/${AWS_IAM_USER}/backup"
 RESTORE_DIR=/var/cloudos/backup
 
-args=( $@ )
-arg_count=${#args[@]}
+if [ -z "${RSKIP_S3}" ] ; then
+  if [ -d "${RESTORE_DIR}" ] ; then
+    rm -rf ${RESTORE_DIR}
+  fi
+  mkdir -p ${RESTORE_DIR}
 
-if [ -d "${RESTORE_DIR}" ] ; then
-  rm -rf ${RESTORE_DIR}
-fi
-mkdir -p ${RESTORE_DIR}
-
-declare -a tars
-if [ ${arg_count} -ge 1 ] ; then
-  tar_names=${args[@]}
-  for tar in ${tar_names[@]} ; do
-    app="$(echo -n $(basename ${tar}) | awk -F '-' '{print $1}')"
-    tar=$(aws s3 ls s3://$S3_ROOT/${app}/ | awk '{print $4}' | sort | grep ${tar} | tail -n 1)
-    if [ -z "${tar}" ] ; then
-      die "Tarball not found: ${tar}"
-    fi
-    tars+=( "s3://$S3_ROOT/${app}/${tar}" )
-  done
-
-  # echo "tars=${tars[@]}" ; exit 1
-  # for each of the restore files, we need to get it from s3, decrypt & un-tar the contents, and then run the
-  # restore chef
-  for file in ${tars[@]} ; do
-    # fetch, decrypt and unroll
-    fetch_app_tarball ${RESTORE_DIR} ${file}
-
-    # run chef-solo
-    #chef-solo -c ${RESTORE_DIR}/${app_name}/restore-solo.rb -j ${RESTORE_DIR}/${app_name}/restore.json || die "Error running chef-solo for app: ${app_name}"
-    echo "would run chef-solo on ${RESTORE_DIR}/${app_name}/restore-solo.rb here"
-
-    # if it succeeded, ensure this app is added to the solo.json run_list
-    # todo: add to solo.json run_list
-    echo "would add ${app_name} to solo.json run_list here"
-  done
-
-else
   echo "no backup list supplied - restoring cloudos latest backup and finding apps from there"
   cloudos_tar=$(aws s3 ls s3://${S3_ROOT}/cloudos/ | awk '{print $4}' | sort | tail -n 1)
+  echo "found cloudos tarball: ${cloudos_tar}"
 
   # fetch, decrypt and unroll cloudos
   fetch_app_tarball ${RESTORE_DIR} s3://${S3_ROOT}/cloudos/${cloudos_tar}
+  echo "fetched tarball: ${RESTORE_DIR}/cloudos/${cloudos_tar}"
+fi
 
-  # determine solo.json and chef user
-  SOLO_JSON=$(find ${RESTORE_DIR}/cloudos/home -type f -name solo.json | head -n 1)
-  if [ -z "${SOLO_JSON}" ] ; then
-    die "No solo.json found in ${RESTORE_DIR}/cloudos/home"
-  fi
+# determine solo.json and chef user
+SOLO_JSON=$(find ${RESTORE_DIR}/cloudos/home -type f -name solo.json | grep -v '/chef-runs/' | head -n 1)
+if [ -z "${SOLO_JSON}" ] ; then
+  die "No solo.json found in ${RESTORE_DIR}/cloudos/home"
+fi
+echo "found chef runlist: ${SOLO_JSON}"
 
-  CHEF_RESTORE_DIR=$(dirname ${SOLO_JSON})
-  CHEF_USER=$(basename $(dirname ${CHEF_RESTORE_DIR}))
-  if [ -z "${CHEF_USER}" ] ; then
-    die "No chef-user found"
-  fi
+CHEF_RESTORE_DIR=$(dirname ${SOLO_JSON})
+CHEF_USER=$(basename $(dirname ${CHEF_RESTORE_DIR}))
+if [ -z "${CHEF_USER}" ] ; then
+  die "No chef-user found"
+fi
 
-  # Create the chef-user if it does not exist
-  if [ $(cat /etc/passwd | grep "${CHEF_USER}:" | wc -l | tr -d '') -eq 0 ] ; then
-    useradd --create-home --home /home/users/${CHEF_USER} --shell /bin/bash --gid wheel --groups rooty ${CHEF_USER}
-  fi
-  CHEF_HOME="$(bash -c "cd ~${CHEF_USER} && pwd")"
+# Create the chef-user if it does not exist
+if [ $(cat /etc/passwd | grep "${CHEF_USER}:" | wc -l | tr -d '') -eq 0 ] ; then
+  useradd --create-home --home /home/users/${CHEF_USER} --shell /bin/bash --gid wheel --groups rooty ${CHEF_USER} || die "Error creating chef user ${CHEF_USER}"
+fi
+CHEF_HOME="$(bash -c "cd ~${CHEF_USER} && pwd")"
 
-  # Stash previous chef-user here, we will need to copy some files from their homedir
-  PREV_CHEF_USER="$(cd $(dirname $0) && basename $(pwd))"
-  PREV_CHEF_USER_HOME="$(bash -c "cd ~${PREV_CHEF_USER} && pwd")"
+# Stash previous chef-user here, we will need to copy some files from their homedir
+PREV_CHEF_USER="$(cd $(dirname $0) && basename $(pwd))"
+PREV_CHEF_USER_HOME="$(bash -c "cd ~${PREV_CHEF_USER} && pwd")"
 
-  echo ${CHEF_USER} > /etc/chef-user
-  BACKUP_HOST="${CHEF_USER}.$(hostname --domain)"
-  hostname ${BACKUP_HOST}
-  echo ${BACKUP_HOST} > /etc/hostname
+echo ${CHEF_USER} > /etc/chef-user
+BACKUP_HOST="${CHEF_USER}.$(hostname | cut -d '.' -f 2-)"
+hostname ${BACKUP_HOST} || die "Error setting hostname to ${BACKUP_HOST}"
+echo ${BACKUP_HOST} > /etc/hostname
 
-  # Restore the original chef-repo
+if [ -z "${RESTORE_APPS}" ] ; then
+  # load apps from solo.json that was restored
+  RESTORE_APPS=$(cat ${SOLO_JSON} | egrep -v '[[:space:]]*//' | ${CHEF_RESTORE_DIR}/JSON.sh | grep \"run_list\", | tr '[]' '  ' | awk '{print $3}' | grep -v '::')
+fi
+
+# Restore the chef-repo
+if [ -z "${RSKIP_INSTALL}" ] ; then
   rsync -avzc ${CHEF_RESTORE_DIR}/* ${CHEF_HOME}/chef/
 
-  # load apps from solo.json that was restored
-  apps=$(cat ${SOLO_JSON} | egrep -v '[[:space:]]*//' | ${CHEF_RESTORE_DIR}/JSON.sh | grep \"run_list\", | tr '[]' '  ' | awk '{print $3}' | grep -v '::')
-
-  RESTORE_JSON="${CHEF_HOME}/chef/restore.json"
-  echo '{ "run_list": [' > ${RESTORE_JSON}
-
-  RESTORE_TIMESTAMPS="${CHEF_HOME}/chef/data_bags/restore/timestamps.json"
-  mkdir -p $(dirname ${RESTORE_TIMESTAMPS})
-  echo '{ "id": "timestamps" }' > ${RESTORE_TIMESTAMPS}
-
-  for app in ${apps} ; do
-    app_tarball=$(aws s3 ls s3://${S3_ROOT}/${app}/ | awk '{print $4}' | sort | tail -n 1)
-
-    if [ ! -z "${app_tarball}" ] ; then
-      if [ "${app}" != "cloudos" ] ; then
-        fetch_app_tarball ${RESTORE_DIR} s3://${S3_ROOT}/${app}/${app_tarball}
-      fi
-
-      timestamp=$(basename ${app_tarball} | sed -e 's/^'${app}'-//' | awk -F '.' '{print $1}')
-      cos json --file ${RESTORE_TIMESTAMPS} --outfile ${RESTORE_TIMESTAMPS} --operation write --path ${app} --value '"'${timestamp}'"'
-    fi
-
-    if [ -f ${CHEF_RESTORE_DIR}/cookbooks/${app}/recipes/lib.rb ] ; then
-      echo "\"recipe[${app}::lib]\"," >> ${RESTORE_JSON}
-    fi
-  done
-  for app in ${apps} ; do
-    if [ -f ${CHEF_RESTORE_DIR}/cookbooks/${app}/recipes/restore.rb ] ; then
-      echo "\"recipe[${app}::restore]\"," >> ${RESTORE_JSON}
-    fi
-  done
-  sed -i '$s/,$//' ${RESTORE_JSON}
-  echo '] }' >> ${RESTORE_JSON}
-
-  echo "wrote restorejson to ${RESTORE_JSON}"
-
-  # ensure chef user owns everything in their own home and in backup dir
-  chown -R ${CHEF_USER} ${CHEF_HOME} ${RESTORE_DIR}
+  # Run the default "install" to ensure everything is OK first
 
   # Nuke kerberos and ldap, they will get reinstalled with proper keys
   KERBEROS_LDAP_PACKAGES=$(cos json -f ${CHEF_HOME}/chef/data_bags/auth/cloudos-manifest.json -o read -p packages | tr -d '[]",')
-  apt-get -y --purge remove ${KERBEROS_LDAP_PACKAGES} && rm -rf /etc/krb* /etc/ldap*
+  apt-get -y --purge remove ${KERBEROS_LDAP_PACKAGES} && rm -rf /etc/krb* /etc/ldap* || die "Error removing kerberos packages"
 
   # Nuke all java processes. This will ensure that all cloudos services are stopped
   killall -9 java
@@ -196,31 +148,86 @@ else
     cat /dev/null > ~cloudos/.first_time_setup && \
     echo "--------------- RESTORE: default chef-solo..." && \
     bash install.sh && \
-    echo "--------------- RESTORE: chef-solo to restore..." && \
-    /usr/bin/chef-solo -c solo.rb -j restore.json -l debug && \
-    echo "--------------- RESTORE: default chef-solo to finalize restoration..." && \
-    bash install.sh && \
-    echo "--------------- RESTORE: restore complete, restarting Apache..." && \
     chmod 755 /var/www && service apache2 restart
   RESTORE_EXIT_VALUE=$?
 
-  # make double-certain that the .first_time_setup file is empty
-  cat /dev/null > ~cloudos/.first_time_setup
+  if [ ${RESTORE_EXIT_VALUE} -ne 0 ] ; then
+    die "Error running default chef install"
+  fi
+fi
 
-  # note: RESTORE_NOTIFY_EMAIL and RESTORE_LOG are set in the RestoreHandler
-  if [ ! -z "${RESTORE_NOTIFY_EMAIL}" ] ; then
-    # Ensure postfix is running
-    service postfix restart
-    sleep 2s
-    if [ $(service postfix status | grep 'not running' | wc -l | tr -d ' ') -gt 0 ] ; then
-      echo "postfix not running, cannot send status email!"
-      exit 1
+RESTORE_TIMESTAMPS="${CHEF_HOME}/chef/data_bags/restore/timestamps.json"
+mkdir -p $(dirname ${RESTORE_TIMESTAMPS}) || die "Error creating restore dir"
+echo '{ "id": "timestamps" }' > ${RESTORE_TIMESTAMPS}
+
+OK_APPS=""
+FAILED_APPS=""
+for app in ${RESTORE_APPS} ; do
+  app_tarball=$(aws s3 ls s3://${S3_ROOT}/${app}/ | awk '{print $4}' | sort | tail -n 1)
+
+  if [ ! -z "${app_tarball}" ] ; then
+    if [ "${app}" != "cloudos" ] ; then
+      fetch_app_tarball ${RESTORE_DIR} s3://${S3_ROOT}/${app}/${app_tarball}
     fi
 
-    if [ ${RESTORE_EXIT_VALUE} -eq 0 ] ; then
-      IPADDR=$(ifconfig | grep -A 2 "^eth" | grep "inet addr:" | tr ':' ' ' | awk '{print $3}')
-      RESTORE_HOST=$(cat /etc/hosts | grep ${IPADDR} | grep -v $(hostname) | awk '{print $2}')
-      sendmail -oi -t <<EOF
+    timestamp=$(basename ${app_tarball} | sed -e 's/^'${app}'-//' | awk -F '.' '{print $1}')
+    cos json --file ${RESTORE_TIMESTAMPS} --outfile ${RESTORE_TIMESTAMPS} --operation write --path ${app} --value '"'${timestamp}'"'
+  fi
+
+  RESTORE_JSON="${CHEF_HOME}/chef/restore-${app}.json"
+  echo '{ "run_list": [' > ${RESTORE_JSON}
+  echo "\"recipe[base::lib]\"," >> ${RESTORE_JSON}
+  echo "\"recipe[apache::lib]\"," >> ${RESTORE_JSON}
+  echo "\"recipe[mysql::lib]\"," >> ${RESTORE_JSON}
+  echo "\"recipe[postgresql::lib]\"," >> ${RESTORE_JSON}
+  echo "\"recipe[java::lib]\"," >> ${RESTORE_JSON}
+  echo "\"recipe[auth::lib]\"," >> ${RESTORE_JSON}
+  echo "\"recipe[email::lib]\"," >> ${RESTORE_JSON}
+
+  if [ -f ${CHEF_RESTORE_DIR}/cookbooks/${app}/recipes/lib.rb ] ; then
+    echo "\"recipe[${app}::lib]\"," >> ${RESTORE_JSON}
+  fi
+  if [ -f ${CHEF_RESTORE_DIR}/cookbooks/${app}/recipes/restore.rb ] ; then
+    echo "\"recipe[${app}::restore]\"," >> ${RESTORE_JSON}
+  fi
+  sed -i '$s/,$//' ${RESTORE_JSON}
+  echo '] }' >> ${RESTORE_JSON}
+
+  echo "wrote restorejson to ${RESTORE_JSON}"
+
+  # ensure chef user owns everything in their own home and in backup dir
+  chown -R ${CHEF_USER} ${CHEF_HOME} ${RESTORE_DIR}
+
+  cd ${CHEF_HOME}/chef && \
+    echo "--------------- RESTORE: chef-solo restore-${app}..." && \
+    /usr/bin/chef-solo -c solo.rb -j ${RESTORE_JSON} -l debug && \
+    chmod 755 /var/www && service apache2 restart
+  RESTORE_EXIT_VALUE=$?
+
+  if [ ${RESTORE_EXIT_VALUE} -eq 0 ] ; then
+    OK_APPS="${OK_APPS} ${app}"
+  else
+    FAILED_APPS="${FAILED_APPS} ${app}"
+  fi
+done
+
+# make double-certain that the .first_time_setup file is empty
+cat /dev/null > ~cloudos/.first_time_setup
+
+# note: RESTORE_NOTIFY_EMAIL and RESTORE_LOG are set in the RestoreHandler
+if [ ! -z "${RESTORE_NOTIFY_EMAIL}" ] ; then
+  # Ensure postfix is running
+  service postfix restart
+  sleep 2s
+  if [ $(service postfix status | grep 'not running' | wc -l | tr -d ' ') -gt 0 ] ; then
+    echo "postfix not running, cannot send status email!"
+    exit 1
+  fi
+
+  if [ -z "${FAILED_APPS}" ] ; then
+    IPADDR=$(ifconfig | grep -A 2 "^eth" | grep "inet addr:" | tr ':' ' ' | awk '{print $3}')
+    RESTORE_HOST=$(cat /etc/hosts | grep ${IPADDR} | grep -v $(hostname) | awk '{print $2}')
+    sendmail -oi -t <<EOF
 From: do-not-reply@$(hostname)
 To: ${RESTORE_NOTIFY_EMAIL}
 Subject: Your $(hostname) cloudstead has been restored
@@ -238,9 +245,9 @@ In the meantime, you can always access your cloudstead with this URL: https://${
 Happy Cloudsteading!
 
 EOF
-
-    else
-      sendmail -oi -t <<EOF
+    echo "All apps restored: ${OK_APPS}"
+  else
+    sendmail -oi -t <<EOF
 From: do-not-reply@$(hostname)
 To: ${RESTORE_NOTIFY_EMAIL}
 Subject: Your $(hostname) cloudstead was not successfully restored
@@ -259,8 +266,11 @@ The last output from the restore process is below.
 $(cat ${RESTORE_LOG} | tail -n 1000)
 
 EOF
-
-    fi
+    die "Failed restoring apps: ${FAILED_APPS} (OK: ${OK_APPS})"
   fi
 
+elif [ ! -z "${FAILED_APPS}" ] ; then
+  die "Failed restoring apps: ${FAILED_APPS} (OK: ${OK_APPS})"
+else
+  echo "All apps restored: ${OK_APPS}"
 fi
